sudo: required

language: node_js

node_js:
  - "stable"

services:
  - docker

cache: 
  yarn: true
  directories:
    - node_modules

env:
  - DOCKER_COMPOSE_VERSION=1.17.1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose up -d
  - cd tests
  - yarn install
  - yarn test